### ISSUE TITLE
Metrics emitted from within group may need dimension name transformation

### ISSUE THREAD

**Issue by ts-sean-foley** [leonyork/xk6-output-timestream#256]
First, thanks for writing this extension and sharing it in office hours as well as in community forums. I have zero go skills today, otherwise I might have already dove in and submitted a PR on this.  

It looks like when I run tests using k6 groups or derivatives, like the chaijs/expect library which I am using, I end up with records with a dimension called 'group' which are successfully written to the table, but it appears that the dimension can't be used in query syntax in a where clause for example. Timestream documentation lists 'group' as a reserved word, which is understandable I suppose. Another interesting reservation is on dimensions or such with names that start with ts_ which I learned the hard way.

One approach might be to prefix "group" with "k6_" but you may have some other thoughts or preferences.  Cheers!

**Comment by leonyork** [comment]
Hey,

Thank you for reporting the issue! I can't see how the `group` dimension would be added by using groups or the chaijs library without explicitly giving the dimension the name `group` (e.g. by adding a `group` tag). Would you be able to provide an example test script where this happens?

I've tried the following test script based off the [tags and groups docs](https://grafana.com/docs/k6/latest/using-k6/tags-and-groups/) and the [k6 chaijs docs](https://k6.io/blog/k6-chai-js/):

```javascript
import { describe, expect } from 'https://jslib.k6.io/k6chaijs/4.3.4.2/index.js';
import { group, sleep } from "k6";
import exec from 'k6/execution';
import http from "k6/http";

export const options = {
  discardResponseBodies: true,
  systemTags: ["status", "method", "url", "error", "error_code", "vu", "iter"],
  tags: {
    test_type: __ENV.TEST_ID || "integration-test",
    instance_id: "1",
  },
};

export default function () {
  //try to add a `group` dimension with `containerGroup`s
  exec.vu.metrics.tags.containerGroup = 'test';

  //try to add a `group` dimension with `group`s
  group('hit the target url', function () {
    http.get(__ENV.TARGET_URL || "https://test.k6.io");
  });
  delete exec.vu.metrics.tags.containerGroup;

  //try to add a `group` dimension using the k6 chaijs library
  describe('crocodiles API', () => {
    describe('should fetch a list of public crocodiles', () => {
      const response = http.get('https://test-api.k6.io/public/crocodiles');

      expect(response.status, 'response status').to.equal(200);
      expect(response).to.have.validJsonBody();
      expect(response.json()).to.have.lengthOf(5);
    });
  });
  sleep(0.5);
}
```

This gives me the following dimensions:

`actual | instance_id | containerGroup | method | expected | this | iter | test_type | url | vu | status`

The only way I could replicate is by adding a tag called `group`:

```javascript
import { sleep } from "k6";
import http from "k6/http";

export const options = {
  discardResponseBodies: true,
  systemTags: ["status", "method", "url", "error", "error_code", "vu", "iter"],
  tags: {
    test_type: __ENV.TEST_ID || "integration-test",
    group: "1",
  },
};

export default function () {
  http.get(__ENV.TARGET_URL || "https://test.k6.io");
  sleep(0.5);
}
```

In this case I was able to query the table by quoting the dimension (i.e. `"group"`):

```sql
SELECT * FROM "dev-xk6-output-timestream-test"."test" WHERE "group" = '1' LIMIT 10
--10 rows

SELECT * FROM "dev-xk6-output-timestream-test"."test" WHERE "group" = '2' LIMIT 10
--0 rows
```

If you could confirm this is the issue, that would be great and hopefully this helps.

Could you elaborate further on

> Another interesting reservation is on dimensions or such with names that start with ts_ which I learned the hard way.

I don't understand the significance of the `ts_` prefix.

**Comment by ts-sean-foley** [comment]
Hello and thank you again. It certainly is pretty strange that my test is emitting output with a group dimension while yours is not and it looks similar to what I am doing. I will work on a sanitized example if this goes on for much longer. I was able to get it to work by correcting my syntax. Dimensions which are not group seem to work without double quotes, but I thought I had tried that before filing the issue. Sorry, I am relatively new to the Timestream flavor of SQL.  Incidentally, the group values I am seeing are my name parameters on my describe(name,functions()) calls but prepended with "::".
<img width="1467" alt="Screenshot 2024-01-08 at 12 01 30 PM" src="https://github.com/leonyork/xk6-output-timestream/assets/43544667/1904e922-512a-4793-bb42-59b760e4be36">

**Comment by ts-sean-foley** [comment]
Also the ts_ thing came about because I was tagging some custom metrics with ts_something due to our normal org name abbreviation.  Apparently Timestream uses such dimensions internally and blucks them from input streams.

**Comment by leonyork** [comment]
I'm happy to keep the issue open while you take a look into this more. I'd prefer to avoid using Timestream keywords as the dimensions if it's a common case! 

Also, interesting on the `ts_` prefixed being reserved by Timestream - I did not know that. 

Let me know how you get on

**Comment by leonyork** [comment]
@ts-sean-foley is there anything more you think we we should do with this issue? If not, I'll close it.
