### ISSUE TITLE
Errors around records with no dimensions

### ISSUE THREAD

**Issue by ts-sean-foley** [leonyork/xk6-output-timestream#257]
When I run tests with the timestream output I am getting some good records ingested but I see some errors messages around records in the batch without dimensions. I am not sure if standard k6 output is generating these, or if it is a custom metric. I may try my hand at adding some debugging output to the extension but I have not done anything in go yet. Here is an example error:

```ERRO[0024] failed to write                               component=timestream count=100 duration=72.525166ms error="unable to write records to timestream: operation error Timestream Write: WriteRecords, https response error StatusCode: 400, RequestID: 2M4VERUETG3GAX6EVVQR4LCI7M, ValidationException: At least one dimension is required for a record." records_address=0xc0122da2c8 t=20.122957185s```

Cheers!

**Comment by leonyork** [comment]
Hey! 

Again, thank you for raising an issue. Would you take a look at [the tags section of the README](https://github.com/leonyork/xk6-output-timestream/blob/main/README.md#tags) - you need to have at least one tag setup. 

Assuming this is the issue, it would be good to make the solution to the problem more obvious in the logs. For example, either:
1. Warn the user if we're about to save a record without any dimensions (this would be a simple length check on the dimensions).
2. Recognise the error (e.g. parse the contents) and give some extra information when it happens.

Firstly, let me know if this was the issue and then we can look at improving the logging.

**Comment by ts-sean-foley** [comment]
Thanks you for looking into this and the other issue I reported. I am digging deeper into both concurrently but adding a generic custom tag in the main script context does seem to make the issue go away. I have a lingering curiosity about the actual components outside of my VUs which are emitting data seemingly without default tags and causing the output extension to not have a single dimension. I suppose it could be scenario metrics.

**Comment by ts-sean-foley** [comment]
Hi and thanks again. This can probably be closed. I missed the note in the tags section but it could perhaps be made more prominent for users not yet using tags, or at least those not tagging anything in the main VU scope. I try to always have a good reason to do something in my code, and had not yet had a reason to apply a custom tag to everything at the top level. I suppose I do now. Cheers.

**Comment by leonyork** [comment]
Agree with making this a little more obvious. If you have any ideas - even if it's just moving the note in the README, then feel free to submit a PR. Otherwise I'll take a look when I have a little more time.

**Comment by leonyork** [comment]
@ts-sean-foley is there anything more you think we should do with this issue beyond updating the README? If not, I'll close the issue.
