### ISSUE TITLE
Does it read environment variables?

### ISSUE THREAD

**Issue by hugogu** [leonyork/xk6-output-timestream#260]
I tried to run this image by this command 

```shell
 docker run --network="host" -i ghcr.io/leonyork/k6:0.48.0-timestream0.8.66 run -o timestream \
        -e K6_TIMESTREAM_DATABASE_NAME='ipay_timestream_db1' \
        -e K6_TIMESTREAM_TABLE_NAME='load-test' \
        -e K6_TIMESTREAM_REGION='us-west-2' \
        -e AWS_REGION='us-west-2'  - < ./scripts/max-vu.js
```
But it doesn't seem to pick up the database name and able name as it declared. The output was like

```log
          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: -
     output: Timestream (:)
```

I checked the source code which claim to handle environment vars but not doing so in code:

```go
// GetConsolidatedConfig combines {default config values + JSON config +
// environment vars config values}, and returns the final result.
func GetConsolidatedConfig(
	jsonRawConf json.RawMessage,
) (Config, error) {
	result := NewConfig()

	if jsonRawConf != nil {
		jsonConf, err := parseJSON(jsonRawConf)
		if err != nil {
			return result, fmt.Errorf("unable to parse json config: %w", err)
		}

		result = result.apply(jsonConf)
	}

	envConfig := Config{}
	if err := envconfig.Process("", &envConfig); err != nil {
		return result, fmt.Errorf("unable to parse env config: %w", err)
	}

	result = result.apply(envConfig)

	return result, nil
}
```
Whereas other output extensions's config consolidation logic does read env from a given parameter.

https://github.com/grafana/xk6-output-influxdb/blob/main/pkg/influxdb/config.go

Maybe I missed some magi code, but would love to know if there is a way to make the environment variable work.

**Comment by leonyork** [comment]
Hey! Thanks for submitted the issue and the PR - yep absolutely right, whilst we pull in the environment variables from the environment we don't pull them in from any parameters passed to the command. I've just kicked off the tests for the PR - let's continue the conversation over there and get this fixed!
