### ISSUE TITLE
Grafana Dashboard not working

### ISSUE THREAD

**Issue by christophersavory** [leonyork/xk6-output-timestream#326]
I tested this extension out yesterday and the dashboard does not seem to be matching up with what is being sent to TimeStream.
The dashboard is looking for a measure called "vus" but that is not being sent to TimeStream.
```
      "targets": [
        {
          "alias": "Active VUs",
          "database": "\"$Database\"",
          "datasource": {
            "uid": "${grafana-timestream-datasource}"
          },
          "dsType": "grafana-timestream-datasource",
          "measure": "vus",
          "policy": "default",
          "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS $__measure\nFROM (\n  SELECT time, SUM($__measure) AS $__measure\n  FROM (\n    SELECT BIN(time, 1s) AS time, AVG(measure_value::double) AS $__measure\n    FROM $__database.$__table\n    WHERE measure_name = '$__measure'\n    AND $__timeFilter\n    GROUP BY BIN(time, 1s)\n    ORDER BY BIN(time, 1s) DESC\n  )\n  GROUP BY time\n)\nGROUP BY BIN(time, $__interval)",
          "refId": "A",
          "resultFormat": "time_series",
          "table": "\"$Table\"",
          "tags": [],
          "waitForResult": true
        }
      ],
      "title": "Virtual Users",
```

<img width="679" alt="image" src="https://github.com/leonyork/xk6-output-timestream/assets/91703489/090ddb74-a9d8-4b65-a83f-2a56b00b6638">
<img width="465" alt="image" src="https://github.com/leonyork/xk6-output-timestream/assets/91703489/47e44a70-a36a-4ec7-84fe-ab11f00dfbb6">

Also the dashboard (grafana/dashboards/loadtest/loadtest.json) is looking for a column called `instance_id` and that column is not being sent to TimeStream.

**Comment by leonyork** [comment]
Hey @christophersavory, thank you for raising this. 

The tags need to be included in options for the test you are running. For example, in the test script used in the integration tests, the [vu tag](https://github.com/leonyork/xk6-output-timestream/blob/main/test/test.js#L6) and [instance_id tag](https://github.com/leonyork/xk6-output-timestream/blob/main/test/test.js#L9) are set in the `options` section of the test script. 

Could you try adding these to the test script you're using? If that works I think we probably need to update [the README](https://github.com/leonyork/xk6-output-timestream/blob/main/README.md?plain=1#L52) to explain that these tags are needed for the dashboard to work.

If that doesn't work, would you be able to provide a test script that replicates the issue?

**Comment by christophersavory** [comment]
It's fixed when I added the tags. Thanks!

**Comment by leonyork** [comment]
np! If it ends up working out well for you please do give the repo a ⭐
