### ISSUE TITLE
Trouble with creating custom docker image with this and another xk6 extension

### ISSUE THREAD

**Issue by ts-sean-foley** [leonyork/xk6-output-timestream#435]
This is a question and I understand if you can't or don't have the time to answer. I am trying to create a docker k6 image built with this and another extension ( https://github.com/szkiba/xk6-chai/issues/3#issue-2622214214 ) and the build fails when I try to build with both but not with either individual extension. 

The error points to go.module issues with a compiler object there in that chai extension, but I wanted to ask you as you have been helpful in the past, and just in case there are some unintended interactions between parts of your extension code and the other I am trying to build with. 

You can see the details of the Dockerfile and error in the issue I linked above. 

Cheers.

**Comment by ts-sean-foley** [comment]
> @ts-sean-foley nice to hear you're still using the extension! Would you be able to help me work out if it's this extension that's not playing well with others or xk6-chai that isn't playing well? Could you try a few other extensions as part of your build - one of the "output" ones would be helpful e.g. xk6-output-elasticsearch.

I can build an image with xk6-chai and xk6-output-elasticsearch together as well as an image with xk6-output-elasticsearch and xk6-output-timestream together.  I also tried a build with all 3 which also fails with the same messaging. 

I also tried a build with the combination of xk6-chai and a different output extension, xk6-output-opentelemetry and observed the same error pointing to undefined compiler things. So it is not isolated to xk6-chai and xk6-output-timestream.

Additionally, I have been able to reproduce this outside of docker just trying to build with xk6 build so this may reduce the complexity of troubleshooting. I appreciate your rapid response and am noting that this is more likely some issue with xk6-chai and compatibility in building with certain other extensions, so please close this issue as you see fit.

Cheers,
Sean

**Comment by leonyork** [comment]
Hi @ts-sean-foley,

Using an older version of xk6-output-timestream seems to work. Here is the updated Dockerfile:

```dockerfile
# Build the k6 binary with the extension
FROM golang:1.21.5 AS builder

RUN go install go.k6.io/xk6/cmd/xk6@latest

# For our example, we'll add support for output of test metrics to InfluxDB v2.
# Feel free to add other extensions using the '--with ...'.
RUN xk6 build \
  --with github.com/szkiba/xk6-chai@latest \
  --with github.com/leonyork/xk6-output-timestream@v0.9.39 \
  --output /k6

# Use the operator's base image and override the k6 binary
FROM grafana/k6:latest
COPY --from=builder /k6 /usr/bin/k6
```

i.e. Using v0.9.39 works

For the moment you could use this version as a workaround.

If I use v0.9.40 then I get the same failure as with the latest version. So the Dockerfile...

```dockerfile
# Build the k6 binary with the extension
FROM golang:1.21.5 AS builder

RUN go install go.k6.io/xk6/cmd/xk6@latest

# For our example, we'll add support for output of test metrics to InfluxDB v2.
# Feel free to add other extensions using the '--with ...'.
RUN xk6 build \
  --with github.com/szkiba/xk6-chai@latest \
  --with github.com/leonyork/xk6-output-timestream@v0.9.40 \
  --output /k6

# Use the operator's base image and override the k6 binary
FROM grafana/k6:latest
COPY --from=builder /k6 /usr/bin/k6
```

... gives me...

```sh
19.55 2024/11/02 11:41:42 [INFO] Building k6
19.55 2024/11/02 11:41:42 [INFO] exec (timeout=0s): /usr/local/go/bin/go mod tidy -compat=1.17
19.68 2024/11/02 11:41:42 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /k6 -ldflags=-w -s -trimpath
54.61 # github.com/szkiba/xk6-chai/chai
54.61 /go/pkg/mod/github.com/szkiba/xk6-chai@v0.1.2/chai/module.go:89:15: comp.Options.Strict undefined (type compiler.Options has no field or method Strict)
54.61 /go/pkg/mod/github.com/szkiba/xk6-chai@v0.1.2/chai/module.go:91:23: comp.Compile undefined (type *compiler.Compiler has no field or method Compile)
60.13 2024/11/02 11:42:22 [INFO] Cleaning up temporary folder: /tmp/buildenv_2024-11-02-1141.2451302339
60.13 2024/11/02 11:42:22 [FATAL] exit status 1
------
Dockerfile:8
--------------------
   7 |     # Feel free to add other extensions using the '--with ...'.
   8 | >>> RUN xk6 build \
   9 | >>>   --with github.com/szkiba/xk6-chai@latest \
  10 | >>>   --with github.com/leonyork/xk6-output-timestream@v0.9.40 \
  11 | >>>   --output /k6
  12 |
--------------------
ERROR: failed to solve: process "/bin/sh -c xk6 build   --with github.com/szkiba/xk6-chai@latest   --with github.com/leonyork/xk6-output-timestream@v0.9.40   --output /k6" did not complete successfully: exit code: 1
```

The key difference between these versions of xk6-output-timestream is that the version of k6 has been [updated from v0.52.0 to v0.53.0](https://github.com/leonyork/xk6-output-timestream/compare/v0.9.39...v0.9.40#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L12). So it looks like a conflict between the versions of the k6 dependency are the issue.

This is supported by the fact that the error is highlighting an undefined method on `compiler` on [this line](https://github.com/szkiba/xk6-chai/blob/master/chai/module.go#L86) and `compiler` [is a k6 dependency](https://github.com/szkiba/xk6-chai/blob/master/chai/module.go#L13)

I haven't got to the bottom of the issue but:

1. I think we first need xk6-chai to update to the latest version of k6 (v0.54.0 I believe). If there's still an issue we can investigate further.
2. Until that happens you can use v0.9.39 of xk6-output-timestream to workaround the issue.

Hopefully this helps and let me know how it goes!

**Comment by ts-sean-foley** [comment]
Leon,

Thank you so much for taking the time to dig into this and providing insights as well as a viable workaround. Thankfully I am not a rush here since the original chai functionality is available in its original external js module. I was just looking to harden my deployment and reduce external js deps when I found out about the xk6 extension. We will ponder our options with this new information as well as follow up on the issue with the xk6-chai folks. Thanks again.

**Comment by leonyork** [comment]
No worries @ts-sean-foley! Let me know if you need anything more once you've taken a look at those options, otherwise feel free to close the issue.
